# ~/.config/starship.toml

# プロンプトの間に適度な空行を挟む
add_newline = true

format = """
$os$directory $git_branch$git_status$git_metrics $rust$nodejs$golang$c$fill$cmd_duration $hostname $time
$character"""

right_format = """"""

[character]
success_symbol = "[>](bold green) "
error_symbol = "[>](bold red) "

[os]
disabled = false
style = "bg:white fg:black bold"
format = "[](fg:white)[$symbol]($style)[](bg:blue fg:white)"

[directory]
style = "bg:blue fg:black bold"
format = "[  $path ]($style)[](fg:blue)"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
style = "bg:bright-black fg:blue bold"
format = "([](fg:bright-black)[on   $branch ]($style))"

[git_status]
style = "bg:bright-black fg:yellow bold"
format = "([［$all_status$ahead_behind］]($style))"
conflicted = "⚑ "
ahead = "⇡${count} "
behind = "⇣${count} "
diverged = "⇕ "
untracked = "?${count} "
stashed = " "
modified = "!${count} "
staged = "+ "
renamed = "» "
deleted = "✘${count} "

[git_metrics]
disabled = false
only_nonzero_diffs = true
format = "([󰦒 ](bg:bright-black fg:blue)[+$added](bg:bright-black fg:green)[-$deleted ](bg:bright-black fg:blue))[](fg:bright-black)"

[fill]
symbol = " "
style = "blue"

[c]
format = '[  $version](bold cyan)'

[golang]
format = '[󰟓  $version](bold cyan) '

[nodejs]
format = '[󰎙  $version](bold green) '

[rust]
format = '[  $version](red bold)'

[hostname]
ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'
disabled = false

[cmd_duration]
min_time = 2000 
style = "fg:yellow bold"
format = "[$duration   ]($style)"

[time]
disabled = false
time_format = "%T"
style = "bg:white fg:bright-black"
format = "[](fg:white)[$time  ]($style)[](fg:white)"

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = " "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = " "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣛 "
Alpine = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = "󰣇 "
Artix = "󰣇 "
EndeavourOS = " "
CentOS = " "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Pop = " "
RockyLinux = " "
