# ~/.config/starship.toml

# プロンプトの間に適度な空行を挟む
add_newline = true

format = """
$os$directory $git_branch$git_status $fill$rust$nodejs$golang$c$cmd_duration $time
$character"""

right_format = """"""

[character]
success_symbol = "[>](bold green) "
error_symbol = "[>](bold red) "

[os]
disabled = false
style = "bg:white fg:black bold"
format = "[](fg:white)[$symbol]($style)[](bg:blue fg:white)"

[directory]
style = "bg:blue fg:black bold"
format = "[  $path ]($style)[](fg:blue)"
truncation_length = 3
fish_style_pwd_dir_length = 1

[git_branch]
style = "bg:bright-black fg:blue bold"
format = "[](fg:bright-black)[on   $branch $git_status]($style)"

[git_status]
style = "bg:bright-black fg:yellow bold"
format = "([［$all_status$ahead_behind］]($style))[](fg:bright-black)"
conflicted = "⚑ "
ahead = "⇡ ${count}"
behind = "⇣ ${count}"
diverged = "⇕ "
untracked = "? "
stashed = " "
modified = "!${count}"
staged = "+ "
renamed = "» "
deleted = "✘ "

[fill]
symbol = " "
style = "blue"

[c]
format = '[  $version](bold cyan)'

[golang]
format = '[󰟓  $version](bold cyan) '

[nodejs]
format = '[󰎙  $version](bold green) '

[rust]
format = '[ $version](red bold)'

[cmd_duration]
min_time = 2000 
style = "bg:yellow fg:black bold"
format = "[](fg:yellow)[took $duration  ]($style)[](fg:yellow)"

[time]
disabled = false
time_format = "%T"
style = "bg:white fg:bright-black"
format = "[](fg:white)[$time  ]($style)[](fg:white)"

[os.symbols]
Macos = " "
openSUSE = " "
RockyLinux = " "
Windows = " "
